### PR TITLE
Update qs dependency

### PR DESCRIPTION
**Pull request by pdehaan**
See https://nodesecurity.io/advisories/qs_dos_extended_event_loop_blocking

### CODE REVIEW

**Comment by DamonOehlman** [comment]
Thanks Peter - I'll bring the other packages up to date also and push an update to npm.

**Comment by DamonOehlman** [comment]
All done - published node module 1.0.1 (marked experimental - avoiding the 0.x range where possible now).

**Comment by pdehaan** [comment]
:beers: Thanks!

For giggles, here's the latest output from `npm outdated` and `nsp audit-shrinkwrap`:

``` sh
$ npm outdated --depth 0

$ npm shrinkwrap --dev
wrote npm-shrinkwrap.json

$ nsp audit-shrinkwrap
Name  Installed  Patched  Vulnerable Dependency
qs      0.6.6     >= 1.x  devcaps > union
```

I filed the **union** issue at flatiron/union#51

**Comment by DamonOehlman** [comment]
NP. I didn't know about the `nsp` package, and now I do. Winning :)

**Comment by pdehaan** [comment]
It's great. They also have Grunt tasks, if you rock GruntJS.
- https://github.com/nodesecurity/grunt-nsp-shrinkwrap
- https://github.com/nodesecurity/grunt-nsp-package

(Both are good, but I prefer the shrinkwrap version since it seems faster.)

**Pull request merged**
